private/build-source-tarball: add newline after the “internal error …” message.

diff --git a/private/build-source-tarball b/private/build-source-tarball
--- a/private/build-source-tarball
+++ b/private/build-source-tarball
@@ -35,7 +35,7 @@ do
         --no-po-check) opt_po_check=; shift;;
         --print-name) opt_print_name=y; shift;;
         --) shift; break;;
-        *) printf '%s: internal error (%s)' "$0" "$1" >&2; exit 1;;
+        *) printf '%s: internal error (%s)\n' "$0" "$1" >&2; exit 1;;
     esac
 done
 
