tools/install-poppler-h-file: use `printf` rather than `echo`.

diff --git a/tools/install-poppler-h-files b/tools/install-poppler-h-files
--- a/tools/install-poppler-h-files
+++ b/tools/install-poppler-h-files
@@ -1,18 +1,20 @@
 #!/bin/sh
 if [ $# -ne 1 ]
 then
-  echo "Usage: $0 <poppler-source-directory>" >&2
+  printf 'Usage: %s <poppler-source-directory>\n' "$0" >&2
   exit 1
 fi
 source_dir=$1
 include_dir=`pkg-config --cflags-only-I poppler-splash | sed -n -e '/^-I/ { s/^-I//; s/ .*//; p; q;}'`
 if [ "x$include_dir" = "x" ]
 then
-  echo "Unable to determine destination directory"
+  printf 'Unable to determine destination directory\n' >&2
   exit 1
 fi
-echo "I will copy header files from $source_dir into $include_dir"
-echo "Press enter to continue"
+cat <<EOF >&2
+I will copy header files from $source_dir into $include_dir
+Press enter to continue
+EOF
 read n
 mkdir -p "$include_dir/goo"
 mkdir -p "$include_dir/splash"
